### PR TITLE
Nitpicky coder changes

### PR DESCRIPTION
**Pull request by sherbang**
Hi Anna,

I took a look at your code and had a couple of minor tweaks.  The main thing is making the end-date dynamic so that you can just replace your dataset file (or update the url to point to a new file) and then the latest data is used throughout without any code changes.

Hope you're doing well through this crazy time.
--
Brian

### CODE REVIEW

**Comment by akonstodata** [comment]
Hey Brian, thanks for checking in!  I actually was just modifying the code to this effect the last hour.  Would you mind taking a look at the update, and then we can see what further updates need to be made?  

Thanks so much again, always looking to improve the code.  Now, more than ever.

**Comment by sherbang** [comment]
I'm not going to be able to reconcile the differences between these branches tonight.

Man, jupyter notebooks make really horrible diffs.

**Comment by akonstodata** [comment]
How about this?  Want to just email me the notebook that you updated?!  I'll include the changes you made in my local repo, and then push to master?  Other ideas welcome :)
Maybe I'll change to Python code for easier diffs (or, make a mirror Python for that).
I'm actually super new to Git (embarrassingly), so please bear with me.
I definitely don't want your work to go to waste - so let me know what you think!  The notebook isn't super long, so if we pull up the notebooks side by side we should be able to see the changes pretty quickly.
I'm making nightly updates with the new data, so I can update tomorrow or the weekend.
Thanks again!!

**Comment by sherbang** [comment]
I needed to get to bed, but fixed the conflicts and pushed a new version this morning.  Let me know what you think.

Switching to .py would certainly make diffs/merges easier, but then won't you need to add code to do the output stuff that jupyter handles for you?  Maybe you already have a solution for this.

Would definitely be interested in data for more states.  Although I also wonder if we're just measuring testing at this point?  Are there a data sources for total hospital admissions as well as total deaths and COVID attributed deaths?

I noticed you're converting datetime compatible objects to date strings in some places where it isn't necessary since pandas supports datetime objects natively.

FYI: For fixing the merge conflict I followed these steps:
```
git checkout git@github.com:sherbang/md_county_covid.git
cd md_county_covid
git remote add upstream git@github.com:akonstodata/md_county_covid.git
git fetch upstream master
git rebase upstream/master
git mergetool # edit all the merge conflicts in a text editor, I'm using gvimdiff
git add code/MD_COVID_Dynamics.ipynb
git rebase --continue
git push --force-with-lease
```

**Comment by akonstodata** [comment]
Awesome, thanks so much Brian!  I merged into master, and pulled it to make today's updates.

Yes, switching to .py would be a bit of a to-do, but if I get more collaborators, might make sense.  What I'd end up doing is maybe replacing the Jupyter notebook with just a nice output that the .py file throws everything into.

There's a lot of different venues with data of differing quality.
-The COVID Tracking project has per state testing and hospitalization data, but not more fine-grained (covidtracking.com).  They also have screenshots from different state agencies (where I am getting my MD county data) - but you then have to type in everything yourself, and is inconsistent between states.
-JHU has global confirmed/deaths/recovered, but keeps changing format, so hard to configure pulls (https://github.com/CSSEGISandData/COVID-19).  
-I'm sure there are others, but this is all happening so fast, it's hard to find something that answers all your questions.  If there's something that you're particularly interested in, I can try to track it down.

Ah, thanks for the tip re: datetime.  I'm almost at my one year 'anniversary' with Python, and still learning :).  Thanks also for the git code.  Even less time working with that.  But, obviously, that's not preventing me from trying to post all this, so I appreciate your help!!

**Pull request merged**
